type: ConvLSTM
name: test
batch_size: ${training.batch_size}
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
hidden_sizes: [16, 16]
height: ${data.height}
width: ${data.width}
device: ${device}
bias: true
context_size: 1