type: DISTANA
name: test
batch_size: ${training.batch_size}
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
hidden_size: 16
layers: 4
height: ${data.height}
width: ${data.width}
device: ${device}
bias: true
context_size: 1