type: TFNO2DModule
name: test
n_modes: [12, 12]
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
hidden_channels: 32
lifting_channels: 256
projection_channels: 256
n_layers: 4
rank: 0.8
bias: true
context_size: 1