type: GraphCastNet
name: test
meshgraph_path: models/graphcast/icospheres_l3.json
static_dataset_path: null
input_height: 32
input_width: 64
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
input_dim_mesh_nodes: 3
input_dim_edges: 4
processor_layers: 16
hidden_layers: 1
hidden_dim: 512
aggregation: sum
activation_fn: silu
norm_type: LayerNorm
use_cugraphops_encoder: false
use_cugraphops_processor: false
use_cugraphops_decoder: false
do_concat_trick: false
recompute_activation: false
partition_size: 1
partition_group_name: null
expect_partitioned_input: false
produce_aggregated_output: true
context_size: 1
