type: ModernUNet
name: modern_unet_pde
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 3  
hidden_channels: [1024, 256, 128, 64] 
activation: th.nn.GELU()  
context_size: 2
norm: true


