type: ModernUNet
name: smallandinverted
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 3  
hidden_channels: [64, 32, 16, 8] 
activation: th.nn.GELU()  
context_size: 2
norm: true
mesh: equirectangular

