type: ModernUNet
name: modernunet_inverted
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 3  
hidden_channels: [136,68,34]
activation: th.nn.GELU()  
context_size: 2
norm: false #true

