type: ModernUNet
name: modern_unet_pde_refiner
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 3  
hidden_channels: [64, 128, 256, 1024] 
#n_convolutions: 1 # single resnet block
activation: th.nn.GELU()  
context_size: 1


