type: PanguWeather
name: test
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
embed_dim: 192
num_heads: [6, 12, 12, 6]
window_size: [2, 6, 12]
patch_size: [1, 1]
n_lat: ${data.height}
n_lon: ${data.width}
context_size: 1

