type: FNOContextModule
name: fno_cntxt2_16
n_modes: [12, 12, 12]
#n_modes: [16, 16]
in_channels: 1
hidden_channels: 32
lifting_channels: 256
projection_channels: 256
out_channels: 1
n_layers: 1
bias: true
context_size: 10