type: GraphCastNetNS
name: graphcast_test
input_height: ${data.height}
input_width: ${data.width}
downscale_factor: ${data.downscale_factor}
context_size: 10
nhop_neighbors: [2]
input_dim_nodes: 1
input_dim_edges: 3
output_dim: 1
processor_layers: 2
num_layers_node_processor: 2
num_layers_edge_processor: 2
hidden_dim_processor: 32
hidden_dim_node_encoder: 32
num_layers_node_encoder: 2
hidden_dim_edge_encoder: 32
num_layers_edge_encoder: 2
hidden_dim_node_decoder: 32
num_layers_node_decoder: 2
aggregation: "sum"
activation_fn: "silu"
norm_type: "LayerNorm"
do_concat_trick: False
num_processor_checkpoint_segments: 0
recompute_activation: False
partition_size: 1
partition_group_name: null
expect_partitioned_input: False
produce_aggregated_output: True
device: ${device}
