type: SwinTransformer
name: swint_test
context_size: 10
pretrain_img_size: ${data.width}
patch_size: 2
in_chans: 1
out_chans: 1
embed_dim: 96
#depths: [2, 2, 6, 2]
#num_heads: [3, 6, 12, 24]
depths: [2, 2, 2, 2]
num_heads: [4, 4, 4, 4]
mlp_ratio: 4
qkv_bias: True
qk_scale: null
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.2
norm_layer: nn.LayerNorm
ape: False
patch_norm: True
frozen_stages: -1
use_checkpoint: False
padding_mode: constant